### ISSUE TITLE
Failed to geocode address [Undefined index: geojson]

### ISSUE THREAD

**Issue by saltymouse** [studioespresso/craft3-easyaddressfield#29]
When saving the following address, the plugin produces an error.

Address:
- Street: `9206 200th St SE`
- Street 2: `Ste C-5`
- Postal Code: `98296`
- City: `Snohomish`
- State: `WA`
- Country: `United States`

Error:

```
yii\base\ErrorException: Undefined index: geojson in /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php:58
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/v...', 58)
#1 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php(58): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/v...', 58, Array)
#2 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php(32): studioespresso\easyaddressfield\services\GeoLocationService->geocodeOSM(Object(studioespresso\easyaddressfield\models\EasyAddressFieldModel))
#3 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php(43): studioespresso\easyaddressfield\services\GeoLocationService->locate(Object(studioespresso\easyaddressfield\models\EasyAddressFieldModel))
#4 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/fields/EasyAddressFieldField.php(208): studioespresso\easyaddressfield\services\FieldService->saveField(Object(studioespresso\easyaddressfield\fields\EasyAddressFieldField), Object(craft\elements\Entry))
#5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3196): studioespresso\easyaddressfield\fields\EasyAddressFieldField->afterElementSave(Object(craft\elements\Entry), false)
#6 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1507): craft\base\Element->afterSave(false)
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2454): craft\elements\Entry->afterSave(false)
#8 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#9 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(376): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#10 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-entry', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/save-en...', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('entries/save-en...', Array)
#17 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/web/index.php(22): yii\base\Application->run()
#20 {main}
```

Notes: 
Entering `Suite` instead of `Ste` gives no error, but there are also no lat-lng coordinates generated either.
Entering `Ste C5` instead of `Ste C-5` also gives no error, but similarly gives no lat-lng coordinates either.

**Comment by janhenckens** [comment]
Hey @saltymouse, I just pushed a fix that makes this address work, can you install and give it a try?
