### ISSUE TITLE
Error when leaving the address empty

### ISSUE THREAD

**Issue by atimoda** [studioespresso/craft3-easyaddressfield#7]
Whenever a try to leave the address empty (and the field is not required), the following error show up in the log, and in the front end it gives the "Internal server error".

```
2018-05-09 12:36:50 [201.81.173.76][1][7f576b267e234c65077018354a1c75fc][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: error_message in /home/storage/9/3d/d8/redemetamorfose1/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php:36
Stack trace:
#0 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/storage/9...', 36)
#1 /home/storage/9/3d/d8/redemetamorfose1/vendor/studioespresso/craft-easyaddressfield/src/services/GeoLocationService.php(36): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/home/storage/9...', 36, Array)
#2 /home/storage/9/3d/d8/redemetamorfose1/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php(42): studioespresso\easyaddressfield\services\GeoLocationService->locate(Object(studioespresso\easyaddressfield\models\EasyAddressFieldModel))
#3 /home/storage/9/3d/d8/redemetamorfose1/vendor/studioespresso/craft-easyaddressfield/src/fields/EasyAddressFieldField.php(205): studioespresso\easyaddressfield\services\FieldService->saveField(Object(studioespresso\easyaddressfield\fields\EasyAddressFieldField), Object(craft\elements\Entry))
#4 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/base/Element.php(1808): studioespresso\easyaddressfield\fields\EasyAddressFieldField->afterElementSave(Object(craft\elements\Entry), true)
#5 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/elements/Entry.php(987): craft\base\Element->afterSave(true)
#6 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/services/Elements.php(463): craft\elements\Entry->afterSave(true)
#7 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/controllers/EntriesController.php(539): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#8 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#9 /home/storage/9/3d/d8/redemetamorfose1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/storage/9/3d/d8/redemetamorfose1/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('save-entry', Array)
#12 /home/storage/9/3d/d8/redemetamorfose1/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#13 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/save-en...', Array)
#14 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/web/Application.php(522): craft\web\Application->runAction('entries/save-en...', Array)
#15 /home/storage/9/3d/d8/redemetamorfose1/vendor/craftcms/cms/src/web/Application.php(258): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /home/storage/9/3d/d8/redemetamorfose1/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/storage/9/3d/d8/redemetamorfose1/public_html/index.php(23): yii\base\Application->run()
#18 {main}
2018-05-09 12:36:34 [201.81.173.76][1][7f576b267e234c65077018354a1c75fc][info][application] $_GET = [
    'p' => 'admin/entries/espacos/new'
]
```

**Comment by janhenckens** [comment]
Could you share your field configuration for the field that is throwing this error? Thanks
